name: star_wars
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ##Packages
  catalog:
    path: packages/data/catalog/
  device:
    path: packages/data/device/
  utility:
    path: packages/core/utility/
  ui:
    path: packages/core/ui/
  home:
    path: packages/features/home/

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  #for managing monorepos
  melos: ^2.9.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  # generate: true
  assets:
    # Add assets from the images directory to the application.
    - assets/images/
